Matches current version of configure.in (summary menu)
git-svn-id: svn+ssh://svn.eu/Dev/importfromcvs/trunk@81458 936e1b1b-40f2-da11-902a-00137254ae57

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2695,8 +2695,8 @@ echo "$as_me: error: I could not find python." >&2;}
       PYTHON_VERSION=2.2
       PYTHON_DIR=${PYTHON_BASE}/lib/python${PYTHON_VERSION}/config
    elif test -d ${PYTHON_BASE}/lib/python1.5 ; then
-      { { echo "$as_me:$LINENO: error: Incorrect version of python. You need 2.0 at least" >&5
-echo "$as_me: error: Incorrect version of python. You need 2.0 at least" >&2;}
+      { { echo "$as_me:$LINENO: error: Incorrect version of python. You need 2.0 at least. Run with -without-python" >&5
+echo "$as_me: error: Incorrect version of python. You need 2.0 at least. Run with -without-python" >&2;}
    { (exit 1); exit 1; }; }
    fi
 
@@ -3952,6 +3952,11 @@ subdirs="$subdirs kernel/src_info/sn"
 
 subdirs="$subdirs kernel/src_info/sn/snsrc"
 
+
+echo ""
+echo "--------- Summary --------------"
+echo "       python: $PYTHON_BASE"
+echo ""
 
 ac_config_files="$ac_config_files Makefile Makefile.common widgets/Makefile.widgets common/src/sdefault.adb docs/Makefile po/Makefile gvd/Makefile.gvd_common gvd/gvd/gvd.ads python/Makefile.python python/python.gpr"
 cat >confcache <<\_ACEOF
