Add handling for the python module
git-svn-id: svn+ssh://svn.eu/Dev/importfromcvs/trunk@81429 936e1b1b-40f2-da11-902a-00137254ae57

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -829,7 +829,8 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --without-ptys          don't use ptys to communicate with the debuggers
+   --without-ptys          don't use ptys to communicate with the debuggers
+ --with-python=<path>     Specify the full path to the Python installation
 
 Some influential environment variables:
   CC          C compiler command
@@ -1326,6 +1327,15 @@ if test "${with_ptys+set}" = set; then
  fi
 else
   USE_PTYS=True
+fi;
+
+
+# Check whether --with-python or --without-python was given.
+if test "${with_python+set}" = set; then
+  withval="$with_python"
+  PYTHON_PATH_WITH=$withval
+else
+  PYTHON_PATH_WITH=""
 fi;
 
 ######## checking for local tools ###
@@ -2623,6 +2633,84 @@ echo "$as_me: error: $GNATMAKE test failed at run time! Check your configuration
    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
 
+
+   if test -z ${PYTHON_PATH_WITH}; then
+      # Extract the first word of "python", so it can be a program name with args.
+set dummy python; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_PYTHON_BASE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $PYTHON_BASE in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_PYTHON_BASE="$PYTHON_BASE" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_PYTHON_BASE="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  test -z "$ac_cv_path_PYTHON_BASE" && ac_cv_path_PYTHON_BASE="no"
+  ;;
+esac
+fi
+PYTHON_BASE=$ac_cv_path_PYTHON_BASE
+
+if test -n "$PYTHON_BASE"; then
+  echo "$as_me:$LINENO: result: $PYTHON_BASE" >&5
+echo "${ECHO_T}$PYTHON_BASE" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+
+      if test x$PYTHON = xno ; then
+         { { echo "$as_me:$LINENO: error: I could not find python." >&5
+echo "$as_me: error: I could not find python." >&2;}
+   { (exit 1); exit 1; }; }
+      else
+         PYTHON_BASE=`dirname ${PYTHON_BASE}`
+         PYTHON_BASE=`dirname ${PYTHON_BASE}`
+      fi
+   else
+      PYTHON_BASE=${PYTHON_PATH_WITH}
+   fi
+
+   if test -d ${PYTHON_BASE}/lib/python2.3 ; then
+      PYTHON_VERSION=2.3
+      PYTHON_DIR=${PYTHON_BASE}/lib
+   elif test -d ${PYTHON_BASE}/lib/python2.2 ; then
+      PYTHON_VERSION=2.2
+      PYTHON_DIR=${PYTHON_BASE}/lib/python${PYTHON_VERSION}/config
+   elif test -d ${PYTHON_BASE}/lib/python1.5 ; then
+      { { echo "$as_me:$LINENO: error: Incorrect version of python. You need 2.0 at least" >&5
+echo "$as_me: error: Incorrect version of python. You need 2.0 at least" >&2;}
+   { (exit 1); exit 1; }; }
+   fi
+
+   if test ${PYTHON_BASE} = "no" ; then
+      echo "checking for python ... run with --without-python"
+      PYTHON_ADA_SOURCE="src2"
+   elif test -d ${PYTHON_BASE}; then
+      echo "checking for python ... ok"
+      PYTHON_ADA_SOURCE="src"
+   else
+      echo "checking for python ... not found"
+      PYTHON_ADA_SOURCE="src2"
+   fi
+
 echo "$as_me:$LINENO: checking whether ${MAKE-make} sets \${MAKE}" >&5
 echo $ECHO_N "checking whether ${MAKE-make} sets \${MAKE}... $ECHO_C" >&6
 set dummy ${MAKE-make}; ac_make=`echo "$2" | sed 'y,./+-,__p_,'`
@@ -3854,6 +3942,10 @@ echo "$as_me: error: Test for GtkAda failed. See the file 'INSTALL' for help." >
 
 
 
+
+
+
+
 subdirs="$subdirs kernel/src_info/sn"
 
 
@@ -3861,7 +3953,7 @@ subdirs="$subdirs kernel/src_info/sn"
 subdirs="$subdirs kernel/src_info/sn/snsrc"
 
 
-ac_config_files="$ac_config_files Makefile Makefile.common widgets/Makefile.widgets common/src/sdefault.adb docs/Makefile po/Makefile gvd/Makefile.gvd_common gvd/gvd/gvd.ads"
+ac_config_files="$ac_config_files Makefile Makefile.common widgets/Makefile.widgets common/src/sdefault.adb docs/Makefile po/Makefile gvd/Makefile.gvd_common gvd/gvd/gvd.ads python/Makefile.python python/python.gpr"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -4367,6 +4459,8 @@ do
   "po/Makefile" ) CONFIG_FILES="$CONFIG_FILES po/Makefile" ;;
   "gvd/Makefile.gvd_common" ) CONFIG_FILES="$CONFIG_FILES gvd/Makefile.gvd_common" ;;
   "gvd/gvd/gvd.ads" ) CONFIG_FILES="$CONFIG_FILES gvd/gvd/gvd.ads" ;;
+  "python/Makefile.python" ) CONFIG_FILES="$CONFIG_FILES python/Makefile.python" ;;
+  "python/python.gpr" ) CONFIG_FILES="$CONFIG_FILES python/python.gpr" ;;
   *) { { echo "$as_me:$LINENO: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
@@ -4468,6 +4562,7 @@ s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@CPP@,$CPP,;t t
 s,@GNATMAKE@,$GNATMAKE,;t t
+s,@PYTHON_BASE@,$PYTHON_BASE,;t t
 s,@SET_MAKE@,$SET_MAKE,;t t
 s,@INSTALL_PROGRAM@,$INSTALL_PROGRAM,;t t
 s,@INSTALL_SCRIPT@,$INSTALL_SCRIPT,;t t
@@ -4500,6 +4595,9 @@ s,@DEFAULT_PS@,$DEFAULT_PS,;t t
 s,@DEFAULT_FONT@,$DEFAULT_FONT,;t t
 s,@HTML_BROWSER@,$HTML_BROWSER,;t t
 s,@OPAQUE_MDI@,$OPAQUE_MDI,;t t
+s,@PYTHON_VERSION@,$PYTHON_VERSION,;t t
+s,@PYTHON_ADA_SOURCE@,$PYTHON_ADA_SOURCE,;t t
+s,@PYTHON_DIR@,$PYTHON_DIR,;t t
 s,@subdirs@,$subdirs,;t t
 CEOF
 
